### ISSUE TITLE
Cacoon work in fabric notebooks

### ISSUE THREAD

**Issue by Palkers76** [Cocoon-Data-Transformation/cocoon#10]
I'm testing cocoon on ms fabric notebooks

installed all fine.
loaded csv for now as pandas df:
```
import pandas as pd
# Load data into pandas DataFrame from "/lakehouse/default/" + "Files/Sales target.csv"
Sales_target = pd.read_csv("/lakehouse/default/" + "Files/Sales target.csv")
Sales_target.head
```

initiated duckdb and cocoon, but table was not created
```
# @title 4. Load data to database (In mem DuckDB for demo) { vertical-output: true }
table_name = "Sales_target"
# For the demo case, we set up an in memory database
Sales_target.columns = [clean_column_name(col) for col in Sales_target.columns]
con = duckdb.connect(database=':memory:')
con.register(table_name, Sales_target)

query_widget, cocoon_workflow = create_cocoon_workflow(con)
```

![image](https://github.com/user-attachments/assets/59d202f0-4b04-44f0-954c-daf16f20ea42)

ValueError                                Traceback (most recent call last)
~/cluster-env/trident_env/lib/python3.10/site-packages/ipywidgets/widgets/widget.py in ?(self, *args, **kwargs)
    191                 ip = get_ipython()
    192                 if ip is None:
    193                     self.log.warning("Exception in callback %s: %s", callback, e, exc_info=True)
    194                 else:
--> 195                     ip.showtraceback()
    196             else:
    197                 value = local_value if local_value is not None else value
    198         return value

~/cluster-env/trident_env/lib/python3.10/site-packages/cocoon_data/__init__.py in ?(b)
  30042             if not database or not schema:
  30043                 output.value = "<div style='color: red;'>Both database and schema must be specified.</div>"
  30044                 return
  30045             else:
> 30046                 success, result = create_schema_and_objects(con, database, schema)
  30047                 output.value = result
  30048                 if success:
  30049                     self.para["database"] = database

**Comment by zachary62** [comment]
Very sorry! It's a new function for snowflake yesterday. 
Could you downgrade cocoon to a stable version:
```
! pip install cocoon_data==0.1.107
```

**Comment by Palkers76** [comment]
it's not failing after upgrade but do not see any table in any schemas. what can be the reason ?
![image](https://github.com/user-attachments/assets/04c08df5-aab3-4d25-9c0e-68430b7be649)

![image](https://github.com/user-attachments/assets/b504abba-fcd1-4791-8428-3caf14205983)

**Comment by zachary62** [comment]
Could you try:
```
con.execute(f"CREATE OR REPLACE TABLE {table_name} AS SELECT * FROM Sales_target")
```
con.register creates a view, that may be slow and expensive to query. So we only allow for tables.

**Comment by Palkers76** [comment]
I have create it but 

1. still query widget showing no tables in all schemas, however I can run select * from TABLE from widget.

![image](https://github.com/user-attachments/assets/bfb507cd-2cb1-4b0d-b851-2fe1b8bf58a3)

2. and success , workflow now showing table

![image](https://github.com/user-attachments/assets/9fbe4fcd-509e-4180-919f-bed7f6fbc271)

**Comment by Palkers76** [comment]
however when I pressed explore. the query seems to be incorrect

![image](https://github.com/user-attachments/assets/27130553-3db7-4098-914d-ec4e3a7677d8)

**Comment by zachary62** [comment]
Got it! 
Yeah "Profile" has issues and I will fix it. Could you try Format first? It is similar to profile and more thorough.
![image](https://github.com/user-attachments/assets/55322a8d-089a-4fc7-842f-596287304eab)

**Comment by zachary62** [comment]
The profile issue shall be fixed in
```
! pip install cocoon_data==0.1.125
```
Note that, to support the latest version of openai, the way to specify api key is changed. See https://github.com/Cocoon-Data-Transformation/cocoon/issues/9#issuecomment-2263948573

**Comment by Palkers76** [comment]
format I think works, however I wonder where dbt files were saved on fabric ;)

![image](https://github.com/user-attachments/assets/e2850a58-7b82-4db9-903c-f7788a9511dc)

**Comment by zachary62** [comment]
In the file directory of your notebook, you should see a folder called "dbt_directory"
The results (sql + ymls) are under /dbt_directory/models/stage

**Comment by Palkers76** [comment]
Solved
