### ISSUE TITLE
NameError: name 'pyodbc' is not defined

### ISSUE THREAD

**Issue by letmestaybehind** [Cocoon-Data-Transformation/cocoon#11]
I get this error on startup!

![image](https://github.com/user-attachments/assets/76781ff8-8c56-4b36-9ab3-77677cb1d2b4)

**Comment by zachary62** [comment]
We currently have pyodbc as part of requirement.
Could you try `pip install pyodbc`
And let me know if `import pyodbc` works
I will also push another patch that removes the pyodbc requirement.

**Comment by zachary62** [comment]
Also, try `create_cocoon_workflow(con)`
We need database as input, not a pandas df

**Comment by letmestaybehind** [comment]
Works now! as i had to do `apt install unixodbc`
