### ISSUE TITLE
cocoon_workflow.start_workflow() not responding

### ISSUE THREAD

**Issue by Palkers76** [Cocoon-Data-Transformation/cocoon#13]
and start not responding

![image](https://github.com/user-attachments/assets/95f1ce7f-b9cc-4b2d-a82c-ef3e5ade98ce)

after running 
```
create_cocoon_workflow(con=con, output=widgets.Output())
```
also not responding

![image](https://github.com/user-attachments/assets/5981d066-d759-485d-bd29-3b69400f03c9)

**Comment by zachary62** [comment]
You need to reassign the cocoon_workflow.
```
query_widget, cocoon_workflow = create_cocoon_workflow(con=con, output=widgets.Output())
cocoon_workflow.start()
```

**Comment by Palkers76** [comment]
I'm pretty sure I tried that as well before I raised that issue and didn't work. now works. magic..
thanks
