### ISSUE TITLE
Error during date column casting (v0.1.153)

### ISSUE THREAD

**Issue by Digma** [Cocoon-Data-Transformation/cocoon#14]
Hi,

I am getting an error in the test colab notebook (v0.1.153): https://colab.research.google.com/github/Cocoon-Data-Transformation/cocoon/blob/main/demo/Cocoon_Stage_Demo.ipynb

I did the data cleaning process and I get the following error after validating the suggested data casting: 

```
---------------------------------------------------------------------------
UnboundLocalError                         Traceback (most recent call last)
/usr/local/lib/python3.10/dist-packages/cocoon_data/__init__.py in on_button_clicked(b)
  20595                 new_table_name = old_table_name + "_casted"
  20596 
> 20597                 schema = table_pipeline.get_schema(con)
  20598                 columns = list(schema.keys())
  20599                 non_affected_columns = [enclose_table_name(col, con=con) for col in columns if col not in affected_columns]

UnboundLocalError: local variable 'con' referenced before assignment
```

![Screenshot 2024-10-28 at 11 45 46](https://github.com/user-attachments/assets/3a10c1ac-a16e-4a26-a916-c6d0049a94cf)

**Comment by zachary62** [comment]
Very sorry about that. The version is actually outdated. 
Could you try v0.1.193? The notebook has also been updated.

**Comment by Digma** [comment]
Thanks, works well now, will close :)
