### ISSUE TITLE
error when excluding columns

### ISSUE THREAD

**Issue by brsolo** [Cocoon-Data-Transformation/cocoon#5]
CreateColumnGrouping() sometimes fails if certain columns are excluded in DecideProjection()

To reproduce, run the workflow on patients.csv and exclude all but the first four columns

![image](https://github.com/Cocoon-Data-Transformation/cocoon/assets/29258822/1b136e2c-9375-4c8e-b0e9-60e22e4dc030)

```
ValueError: Validation failed with the following error(s):
Extra attributes: id
Missing attributes: Id
 Are attributes in the leaf as an array [att1, att2]?
```

**Comment by zachary62** [comment]
This is expected because LLM refers to "Id" as "id". 
The solution is to disable the cache and let the LLM retry.

**Comment by zachary62** [comment]
https://github.com/Cocoon-Data-Transformation/cocoon/commit/2e8979138d65f053012fd9b96d5018aaf5739054
The above commit implements trials for the column group
