### ISSUE TITLE
azure openai error

### ISSUE THREAD

**Issue by Palkers76** [Cocoon-Data-Transformation/cocoon#9]
I'm trying to use azure openai and set openai.api_type ='azure' but getting error below "AttributeError: module 'openai' has no attribute 'gpt4_engine'"
please advice what is wrong
my code:
`
# @title 2. Provide LLM API Key { vertical-output: true }
from cocoon_data import *

openai.api_type ='azure'
openai_key = 'xxxxxxxxxxxxxxxx' # @param {type:"string"}
#claude_key = '' # @param {type:"string"}

# test if LLM works
test_message = "hello" # @param {type:"string"}
cocoon_llm_setting['openai_model'] = "gpt-4-turbo"
# set up your openai api key
openai.api_key = openai_key

messages = [{"role": "user", "content": test_message}]
response = call_llm_chat(messages, temperature=0.1, top_p=0.1)
print(response['choices'][0]['message']['content'])
`

Cell In[22], line 17
     12 openai.api_key = openai_key
     16 messages = [{"role": "user", "content": test_message}]
---> 17 response = call_llm_chat(messages, temperature=0.1, top_p=0.1)
     18 print(response['choices'][0]['message']['content'])

File ~/cluster-env/trident_env/lib/python3.10/site-packages/cocoon_data/llm.py:202, in call_llm_chat(messages, temperature, top_p, use_cache)
    198     response = convert_gemini_to_openai(responses)
    200 elif openai.api_type == 'azure':
    201     response = openai.ChatCompletion.create(
--> 202         engine = openai.gpt4_engine,
    203         temperature=temperature,
    204         top_p=top_p,
    205         messages=messages
    206     )
    208 elif openai.api_type == 'open_ai':
    210     response = openai.ChatCompletion.create(
    211         model="gpt-4-turbo",
    212         temperature=temperature,
    213         top_p=top_p,
    214         messages=messages
    215     )

AttributeError: module 'openai' has no attribute 'gpt4_engine'

**Comment by zachary62** [comment]
Hey @Palkers76 ,

For Azure, you need to specify your deployed model engine. 
E.g., my azure account looks like this:
![image](https://github.com/user-attachments/assets/ae71d8d7-faab-44e8-9790-5889d213335f)

And my model engine deployment in my Azure OpenAI Studio is:
![image](https://github.com/user-attachments/assets/ca5c4025-11e5-4284-bcbb-bc5252d322ed)

So my setup is:
```
openai.api_type = "azure"
openai.api_base ="https://zachgpt4.openai.azure.com/"
openai.api_key = "xxx"
openai.api_version = "2023-12-01-preview"
openai.gpt4_engine = "zach_gpt_turbo"
```

**Comment by Palkers76** [comment]
Thanks, 
are you planning to support higher version of openai?

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cocoon-data 0.1.122 requires openai==0.27.8, but you have openai 1.37.1 which is incompatible.

**Comment by Palkers76** [comment]
works,

**Comment by zachary62** [comment]
cocoon >= 0.1.125 now supports openai  >= 1.0.0
But the way to set up is a bit different. Example for azure:

```
# if you use Azure Open AI
cocoon_llm_setting['api_type'] = "azure"
# azure openai key and endpoint
cocoon_llm_setting['api_key'] = "xxx"
cocoon_llm_setting['api_base'] = "https://zachgpt4.openai.azure.com/"
# deployed model in azure openai
cocoon_llm_setting['api_version'] = "2023-12-01-preview"
cocoon_llm_setting['azure_engine'] = "zach_gpt_turbo"
```
